#!/usr/bin/expect
set timeout -1
set t0 [exec date +%s]

spawn qemu-system-x86_64 -cpu host -enable-kvm -m 4096 -nic user,hostfwd=tcp::13650-:22 -drive file=disk.qcow2,format=qcow2 -device intel-hda -device hda-duplex -usb -rtc base=localtime -monitor stdio

# Complete
set finished 0
while {$finished <= 0} {
    sleep 5
    send "screendump dump.ppm\r"
    set t [exec date +%s]
    set dt [expr {$t - $t0}]
    send_user "Wait. (dt = $dt s)\n"
    # exec ./readppm dump.ppm 768010 >@stdout
    if {[exec ./readppm dump.ppm 768010] eq "203 228 239"} {
        set finished 1
    }
    exec rm -f dump.ppm
}

set t [exec date +%s]
set dt [expr {$t - $t0}]
send_user "Open powershell. (dt = $dt s)\n"
send "sendkey meta_l-r\r"
sleep 2
send "sendkey p\r"
send "sendkey o\r"
send "sendkey w\r"
send "sendkey e\r"
send "sendkey r\r"
send "sendkey s\r"
send "sendkey h\r"
send "sendkey e\r"
send "sendkey l\r"
send "sendkey l\r"
send "sendkey spc\r"
send "sendkey minus\r"
send "sendkey n\r"
send "sendkey o\r"
send "sendkey p\r"
send "sendkey r\r"
send "sendkey o\r"
send "sendkey f\r"
send "sendkey i\r"
send "sendkey l\r"
send "sendkey e\r"
send "sendkey spc\r"
send "sendkey minus\r"
send "sendkey i\r"
send "sendkey n\r"
send "sendkey p\r"
send "sendkey u\r"
send "sendkey t\r"
send "sendkey f\r"
send "sendkey o\r"
send "sendkey r\r"
send "sendkey m\r"
send "sendkey a\r"
send "sendkey t\r"
send "sendkey spc\r"
send "sendkey n\r"
send "sendkey o\r"
send "sendkey n\r"
send "sendkey e\r"
send "sendkey spc\r"
send "sendkey minus\r"
send "sendkey e\r"
send "sendkey x\r"
send "sendkey e\r"
send "sendkey c\r"
send "sendkey u\r"
send "sendkey t\r"
send "sendkey i\r"
send "sendkey o\r"
send "sendkey n\r"
send "sendkey p\r"
send "sendkey o\r"
send "sendkey l\r"
send "sendkey i\r"
send "sendkey c\r"
send "sendkey y\r"
send "sendkey spc\r"
send "sendkey b\r"
send "sendkey y\r"
send "sendkey p\r"
send "sendkey a\r"
send "sendkey s\r"
send "sendkey s\r"
send "sendkey spc\r"
send "sendkey minus\r"
send "sendkey c\r"
send "sendkey o\r"
send "sendkey m\r"
send "sendkey m\r"
send "sendkey a\r"
send "sendkey n\r"
send "sendkey d\r"
send "sendkey spc\r"
send "sendkey i\r"
send "sendkey e\r"
send "sendkey x\r"
send "sendkey spc\r"
send "sendkey shift-apostrophe\r"
send "sendkey shift-9\r"
send "sendkey shift-9\r"
send "sendkey shift-n\r"
send "sendkey e\r"
send "sendkey w\r"
send "sendkey minus\r"
send "sendkey shift-o\r"
send "sendkey b\r"
send "sendkey j\r"
send "sendkey e\r"
send "sendkey c\r"
send "sendkey t\r"
send "sendkey spc\r"
send "sendkey shift-s\r"
send "sendkey y\r"
send "sendkey s\r"
send "sendkey t\r"
send "sendkey e\r"
send "sendkey m\r"
send "sendkey dot\r"
send "sendkey shift-n\r"
sleep 1
send "sendkey e\r"
send "sendkey t\r"
send "sendkey dot\r"
send "sendkey shift-w\r"
send "sendkey e\r"
send "sendkey b\r"
send "sendkey shift-c\r"
send "sendkey l\r"
send "sendkey i\r"
send "sendkey e\r"
send "sendkey n\r"
send "sendkey t\r"
send "sendkey shift-0\r"
send "sendkey dot\r"
send "sendkey shift-d\r"
send "sendkey o\r"
send "sendkey w\r"
send "sendkey n\r"
send "sendkey l\r"
send "sendkey o\r"
send "sendkey a\r"
send "sendkey d\r"
send "sendkey shift-s\r"
send "sendkey t\r"
send "sendkey r\r"
send "sendkey i\r"
send "sendkey n\r"
send "sendkey g\r"
send "sendkey shift-9\r"
send "sendkey apostrophe\r"
send "sendkey h\r"
send "sendkey t\r"
send "sendkey t\r"
send "sendkey p\r"
send "sendkey s\r"
send "sendkey shift-semicolon\r"
send "sendkey slash\r"
send "sendkey slash\r"
send "sendkey c\r"
send "sendkey h\r"
send "sendkey o\r"
send "sendkey c\r"
send "sendkey o\r"
send "sendkey l\r"
send "sendkey a\r"
send "sendkey t\r"
send "sendkey e\r"
send "sendkey y\r"
send "sendkey dot\r"
send "sendkey o\r"
send "sendkey r\r"
send "sendkey g\r"
send "sendkey slash\r"
send "sendkey i\r"
send "sendkey n\r"
send "sendkey s\r"
send "sendkey t\r"
send "sendkey a\r"
send "sendkey l\r"
send "sendkey l\r"
send "sendkey dot\r"
send "sendkey p\r"
send "sendkey s\r"
send "sendkey 1\r"
send "sendkey apostrophe\r"
send "sendkey shift-0\r"
send "sendkey shift-0\r"
send "sendkey shift-apostrophe\r"

interact

send "sendkey ctrl-shift-kp_enter\r"
sleep 2
send "sendkey left\r"
send "sendkey kp_enter\r"
sleep 10

set t [exec date +%s]
set dt [expr {$t - $t0}]
send_user "Started. (dt = $dt s)\n"

